"""update_repository_and_task_layer

Revision ID: 72e0c2c84dce
Revises: 8c36e233f4cf
Create Date: 2025-01-08 02:13:30.911026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e0c2c84dce'
down_revision: Union[str, None] = '8c36e233f4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 