"""update_user_project_relationships

Revision ID: 8c36e233f4cf
Revises: e92d1c917fab
Create Date: 2025-01-08 02:10:34.509136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c36e233f4cf'
down_revision: Union[str, None] = 'e92d1c917fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 