"""create_all_tables

Revision ID: 94d60e3ea6f7
Revises: 53c1cd4d44d6
Create Date: 2025-01-08 16:01:45.978384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94d60e3ea6f7'
down_revision: Union[str, None] = '53c1cd4d44d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_based_advertorials_project_id', table_name='story_based_advertorials')
    op.drop_index('ix_story_based_advertorials_user_id', table_name='story_based_advertorials')
    op.drop_table('story_based_advertorials')
    op.drop_index('ix_value_based_advertorials_project_id', table_name='value_based_advertorials')
    op.drop_index('ix_value_based_advertorials_user_id', table_name='value_based_advertorials')
    op.drop_table('value_based_advertorials')
    op.drop_index('ix_informational_advertorials_project_id', table_name='informational_advertorials')
    op.drop_index('ix_informational_advertorials_user_id', table_name='informational_advertorials')
    op.drop_table('informational_advertorials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informational_advertorials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='informational_advertorials_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='informational_advertorials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='informational_advertorials_pkey')
    )
    op.create_index('ix_informational_advertorials_user_id', 'informational_advertorials', ['user_id'], unique=False)
    op.create_index('ix_informational_advertorials_project_id', 'informational_advertorials', ['project_id'], unique=False)
    op.create_table('value_based_advertorials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='value_based_advertorials_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='value_based_advertorials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='value_based_advertorials_pkey')
    )
    op.create_index('ix_value_based_advertorials_user_id', 'value_based_advertorials', ['user_id'], unique=False)
    op.create_index('ix_value_based_advertorials_project_id', 'value_based_advertorials', ['project_id'], unique=False)
    op.create_table('story_based_advertorials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='story_based_advertorials_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='story_based_advertorials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='story_based_advertorials_pkey')
    )
    op.create_index('ix_story_based_advertorials_user_id', 'story_based_advertorials', ['user_id'], unique=False)
    op.create_index('ix_story_based_advertorials_project_id', 'story_based_advertorials', ['project_id'], unique=False)
    # ### end Alembic commands ### 