"""create_analysis_tables

Revision ID: de40ec485422
Revises: 72e0c2c84dce
Create Date: 2025-01-08 02:18:43.650896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de40ec485422'
down_revision: Union[str, None] = '72e0c2c84dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('raw_perplexity_response', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_avatar_analysis_project_query', 'avatar_analysis', ['project_id', 'query'], unique=False)
    op.create_index('ix_avatar_analysis_task_id', 'avatar_analysis', ['task_id'], unique=True)
    op.create_index('ix_avatar_analysis_user_project', 'avatar_analysis', ['user_id', 'project_id'], unique=False)
    op.create_table('pain_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('raw_perplexity_response', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_pain_analysis_project_query', 'pain_analysis', ['project_id', 'query'], unique=False)
    op.create_index('ix_pain_analysis_task_id', 'pain_analysis', ['task_id'], unique=True)
    op.create_index('ix_pain_analysis_user_project', 'pain_analysis', ['user_id', 'project_id'], unique=False)
    op.create_table('pattern_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('raw_perplexity_response', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_pattern_analysis_project_query', 'pattern_analysis', ['project_id', 'query'], unique=False)
    op.create_index('ix_pattern_analysis_task_id', 'pattern_analysis', ['task_id'], unique=True)
    op.create_index('ix_pattern_analysis_user_project', 'pattern_analysis', ['user_id', 'project_id'], unique=False)
    op.create_table('product_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('raw_perplexity_response', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_product_analysis_project_query', 'product_analysis', ['project_id', 'query'], unique=False)
    op.create_index('ix_product_analysis_task_id', 'product_analysis', ['task_id'], unique=True)
    op.create_index('ix_product_analysis_user_project', 'product_analysis', ['user_id', 'project_id'], unique=False)
    op.create_table('question_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('raw_perplexity_response', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_question_analysis_project_query', 'question_analysis', ['project_id', 'query'], unique=False)
    op.create_index('ix_question_analysis_task_id', 'question_analysis', ['task_id'], unique=True)
    op.create_index('ix_question_analysis_user_project', 'question_analysis', ['user_id', 'project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_analysis_user_project', table_name='question_analysis')
    op.drop_index('ix_question_analysis_task_id', table_name='question_analysis')
    op.drop_index('ix_question_analysis_project_query', table_name='question_analysis')
    op.drop_table('question_analysis')
    op.drop_index('ix_product_analysis_user_project', table_name='product_analysis')
    op.drop_index('ix_product_analysis_task_id', table_name='product_analysis')
    op.drop_index('ix_product_analysis_project_query', table_name='product_analysis')
    op.drop_table('product_analysis')
    op.drop_index('ix_pattern_analysis_user_project', table_name='pattern_analysis')
    op.drop_index('ix_pattern_analysis_task_id', table_name='pattern_analysis')
    op.drop_index('ix_pattern_analysis_project_query', table_name='pattern_analysis')
    op.drop_table('pattern_analysis')
    op.drop_index('ix_pain_analysis_user_project', table_name='pain_analysis')
    op.drop_index('ix_pain_analysis_task_id', table_name='pain_analysis')
    op.drop_index('ix_pain_analysis_project_query', table_name='pain_analysis')
    op.drop_table('pain_analysis')
    op.drop_index('ix_avatar_analysis_user_project', table_name='avatar_analysis')
    op.drop_index('ix_avatar_analysis_task_id', table_name='avatar_analysis')
    op.drop_index('ix_avatar_analysis_project_query', table_name='avatar_analysis')
    op.drop_table('avatar_analysis')
    # ### end Alembic commands ### 