"""Remove keywords from CommunityAnalysis

Revision ID: ed40f5d6db72
Revises: d04c04aeefb5
Create Date: 2025-01-02 00:57:18.956302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed40f5d6db72'
down_revision: Union[str, None] = 'd04c04aeefb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
